################################# Default configuration ###################
baseURL = "https://www.javinator9889.com/pArm"
title = "Meghna"
theme = "meghna"
themesDir = "themes"

dataDir = "pArm/data"
contentDir = "pArm/content"
publishDir = "public/pArm"
assetsDir = "pArm/assets"
staticDir = "pArm/static"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"

################### English Navigation ########################
[[Languages.en.menu.main]]
name = "about"
url = "#about"
weight = 1

[[Languages.en.menu.main]]
name = "services"
url = "#services"
weight = 2

[[Languages.en.menu.main]]
name = "portfolio"
url = "#portfolio"
weight = 3

[[Languages.en.menu.main]]
name = "team"
url = "#team"
weight = 4

[[Languages.en.menu.main]]
name = "pricing"
url = "#pricing"
weight = 5

[[Languages.en.menu.main]]
name = "blog"
url = "#blog"
weight = 6

[[Languages.en.menu.main]]
name = "contact"
url = "#contact"
weight = 7

[[Languages.en.menu.main]]
name = "themefisher"
url = "https://themefisher.com/"
weight = 8


################### French Navigation ########################
[[Languages.es.menu.main]]
name = "acerca de"
url = "#about"
weight = 1

[[Languages.es.menu.main]]
name = "servicios"
url = "#services"
weight = 2

[[Languages.es.menu.main]]
name = "portfolio"
url = "#portfolio"
weight = 3

[[Languages.es.menu.main]]
name = "equipo"
url = "#team"
weight = 4

[[Languages.es.menu.main]]
name = "precios"
url = "#pricing"
weight = 5

[[Languages.es.menu.main]]
name = "blog"
url = "#blog"
weight = 6

[[Languages.es.menu.main]]
name = "contact"
url = "#contact"
weight = 7

[[Languages.es.menu.main]]
name = "themefisher"
url = "https://themefisher.com/"
weight = 8

############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
description = "Responsive Multipurpose Parallax Hugo Template"
author = "Themefisher"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = false
preloader = "images/logo.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

# google map
[params.map]
enable = false

############################# social icons ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
link = "#"


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"

################################ France Language ########################
[Languages.es]
languageName = "Es"
languageCode = "es-es"
contentDir = "content/spanish"
weight = 2
home = "Inicio"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"
